name: CI Sanity

on:
  push:
    branches: [ develop, feature/**, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Hello CI
        run: |
          echo "✅ CI está funcionando"
          node -v
          npm -v
