version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: mediflow-db
    restart: always
    environment:
      POSTGRES_USER: mediflow-db        # usuario inicial
      POSTGRES_PASSWORD: 9413    # contraseña de ese usuario
      POSTGRES_DB: mediflow     # base de datos inicial
    ports:
      - "5432:5432"             # mapea puerto local 5432 -> puerto del contenedor
    volumes:
      - pgdata:/var/lib/postgresql/data  # persistencia en tu disco
    healthcheck:                # chequeo automático de que la DB está lista
      test: ["CMD-SHELL", "pg_isready -U app -d mediflow"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
