name: Backend CI

on:
  push:
    branches: [ develop, main, feature/** ]
  pull_request:
    branches: [ develop, main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mediflow-back
    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: mediflow_ci

        options: >-
          --health-cmd="pg_isready -U app -d mediflow_ci"
          --health-interval=5s --health-timeout=3s --health-retries=10

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: app
      DB_PASS: app
      DB_NAME: mediflow_ci
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: mediflow-back/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run DB migrations (TypeORM)
        run: npx ts-node ./node_modules/typeorm/cli.js -d ./data-source.ts migration:run

      - name: Done
        run: echo "✅ Backend CI OK"
